### ISSUE TITLE
Throws when package.json is unparsable

### ISSUE THREAD

**Issue by quarterto** [sindresorhus/atom-linter-xo#53] opened 2016-11-24 10:56 UTC
This is probably an issue in `linter` itself, because the thrown error means you can't save files at all (e.g. to fix the broken package.json 😕). We could paper over it in linter-xo with `dependsOnXO(cwd).catch(() => false)` but I'm not sure if that's the right answer

**Comment by marionebl** [comment] 2016-11-24 18:09
I think throwing and displaying the big red alert box in the process is actually the right thing to do in this case. 

I do not quite understand how the exception prevents you from saving any file, could you expand on that bit?

**Comment by quarterto** [comment] 2016-11-24 18:14
I don't know what's causing it, but when I save, `linter` triggers, `linter-xo` throws the error, and the save never actually happens.

I disagree that the big red error box is appropriate here. `linter-xo` tries to parse every `package.json` even if it's not going to run. It's annoying to get errors from a package you're not actively using.

**Comment by sindresorhus** [comment] 2016-11-24 18:24
I agree it shouldn't prevent saving, but if we swallow the error the user wouldn't know that their package.json is invalid, and would think XO is not working.

**Comment by marionebl** [comment] 2016-11-24 18:27
Could you post the stacktrace and/or a screenshot as well as the currently used `atom-linter-xo` version?

**Comment by quarterto** [comment] 2016-11-24 18:28
<img width="564" alt="screenshot 2016-11-24 18 28 27" src="https://cloud.githubusercontent.com/assets/631757/20607859/ce1dd0ee-b273-11e6-89b9-86e79844bb38.png">


**Atom Version**: 1.13.0-beta5
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12
**Thrown From**: [linter-xo](https://github.com/sindresorhus/atom-linter-xo) package, v0.20.1


### Stack Trace

Uncaught JSONError

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:1030

JSONError: Unexpected token '"' at 16:7 in Users/matthew.brennan/Projects/Busboy/package.json
      "envify"
      ^
    at module.exports (/Users/matthew.brennan/.atom/packages/linter-xo/node_modules/parse-json/index.js:27:17)
    at parse (/Users/matthew.brennan/.atom/packages/linter-xo/node_modules/load-json-file/index.js:8:29)
    at module.exports.sync.fp (/Users/matthew.brennan/.atom/packages/linter-xo/node_modules/load-json-file/index.js:11:29)
    at findPkg (/Users/matthew.brennan/.atom/packages/linter-xo/index.js:30:12)
    at /Users/matthew.brennan/.atom/packages/linter-xo/index.js:170:19
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1122:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1114:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:904:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:738:18)
    at Pane.saveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:693:35)
    at atom-workspace.core:save (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:07.0 vim-mode-plus:move-left (input.hidden-input)
     -0:06.8.0 vim-mode-plus:delete-right (input.hidden-input)
  2x -0:05.6.0 core:save (input.hidden-input)
     -0:00.9.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
     -0:00.1.0 core:save (input.hidden-input)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "relative-numbers",
      "linter-jshint",
      "web-view",
      "atom-html-preview",
      "linter-tslint",
      "atom-typescript",
      "term3",
      "linter-markdown",
      "linter-hlint",
      "language-haskell",
      "Hydrogen",
      "ink",
      "atom-webbrowser",
      "Parinfer",
      "linter-clojure",
      "autocomplete-snippets",
      "language-toml",
      "language-csharp",
      "archive-view",
      "welcome",
      "styleguide",
      "background-tips",
      "autocomplete-atom-api",
      "language-perl",
      "spell-check",
      "line-ending-selector",
      "markdown-preview",
      "metrics",
      "encoding-selector",
      "easy-motion-redux",
      "tab-switcher",
      "markdown-scroll-sync",
      "move-status-items",
      "snippets"
    ],
    "telemetryConsent": "no",
    "themes": [
      "nucleus-dark-ui",
      "makika-syntax"
    ],
    "useCustomTitleBar": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-beautify, v0.29.13 (active)
atom-css-comb, v3.1.0 (inactive)
atom-handlebars, v1.3.0 (active)
atom-ternjs, v0.16.1 (active)
atomatigit, v1.5.5 (active)
autocomplete-modules, v1.6.7 (active)
autocomplete-paths, v1.0.2 (active)
autocomplete-sass, v0.1.0 (active)
autoupdate-packages, v1.3.1 (active)
blame, v0.10.2 (inactive)
build, v0.67.0 (active)
busy, v0.7.0 (active)
css-snippets, v1.1.0 (active)
docblockr, v0.8.7 (active)
environment, v1.3.1 (active)
ex-mode, v0.13.1 (inactive)
expand-region, v0.2.6 (inactive)
file-icons, v1.7.25 (active)
git-history, v3.2.0 (inactive)
git-plus, v5.25.5 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
javascript-snippets, v1.2.1 (active)
language-diff, v0.6.0 (active)
language-latex, v1.0.0 (active)
language-scheme, v1.4.0 (active)
language-vcl, v0.1.0 (active)
latex, v0.41.0 (inactive)
latexer, v0.3.0 (active)
lines, v0.13.1 (inactive)
linter, v1.11.20 (active)
linter-csslint, v1.3.3 (active)
linter-eslint, v8.0.0 (active)
linter-handlebars, v2.3.4 (active)
linter-jshint, v3.0.1 (inactive)
linter-jsonlint, v1.3.0 (active)
linter-sass-lint, v1.7.4 (active)
linter-xo, v0.20.1 (active)
makika-light-syntax, v0.0.0 (inactive)
makika-syntax, v0.0.0 (active)
maximize-panes, v0.2.0 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.26.3 (active)
move-panes, v0.2.0 (inactive)
nucleus-dark-ui, v0.10.18 (active)
pdf-view, v0.53.0 (active)
pigments, v0.38.0 (active)
project-plus, v0.9.0 (active)
proton-mode, v0.13.0 (active)
react, v0.16.1 (active)
react-snippets, v0.5.0 (active)
recent-files-fuzzy-finder, v0.2.4 (active)
relative-numbers, v0.5.1 (inactive)
release-notes, v0.53.0 (active)
status-bar, v1.7.0 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
theme-switch, v0.4.0 (inactive)
transpose-selection, v1.1.0 (active)
vim-mode-plus, v0.50.0 (active)
vim-mode-plus-ex-mode, v0.5.0 (inactive)
zentabs, v0.8.7 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.7.0 (active)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by marionebl** [comment] 2016-11-25 08:47
`Projects/Busboy/package.json` reads as of this was your own project root. Correct?

As for why and how the save is prevented for your `package.json` I have no idea. I am pretty sure this is not caused by `linter-xo` as it [won't do anything](https://github.com/sindresorhus/atom-linter-xo/blob/master/index.js#L8) when editing/saving json files.

**Comment by marionebl** [comment] 2016-12-13 02:03
@quarterto I close this given

1. Throwing for invalid json is intended behaviour
2. There is no possibility I know of for linter-xo to cause the failed save operations

**Closed** 2016-12-13 02:04 UTC
