### ISSUE TITLE
Strange bug in combination with ava/no-ignored-test-files

### ISSUE THREAD

**Issue by leo** [sindresorhus/atom-linter-xo#30] opened 2016-07-22 10:21 UTC
<img width="743" alt="screen shot 2016-07-22 at 12 11 21" src="https://cloud.githubusercontent.com/assets/6170607/17054236/67c14634-5006-11e6-8d35-c2cbdfc00d56.png">

This doesn't make any sense at all. The file is located at `test/index.js`, so it should just work fine. Or am I missing something?
## How to reproduce

With linter-xo enabled in Atom:
1. Clone [args](https://github.com/leo/args) and `npm install`
2. Remove [this line](https://github.com/leo/args/blob/6caf585074740e0461c0e9df7ca96a7a5b05d0f1/package.json#L53)
3. Open `test/index.js`

**Comment by sindresorhus** [comment] 2016-08-27 14:37
Weird. I'm unable to reproduce.

Can you try to `rm -rf node_modules && npm install` and also reinstall the Atom plugin?

This plugin had a problem with that rule previously, but it was fixed a long time ago: https://github.com/sindresorhus/atom-linter-xo/commit/e4fbc732bb469cddfec16eadcc681669c1143dd5

**Comment by leo** [comment] 2016-08-27 21:04
Just tried exactly that: Didn't work. Have tried to reproduce it with my code?

I'm on the latest node/os/everything.

**Comment by sindresorhus** [comment] 2016-08-27 21:23
Yes, I followed your steps. Latest macOS, Atom 1.9.9, atom-linter-xo 0.17.0.

**Comment by leo** [comment] 2016-08-27 21:29
Maybe it's related to [my linter config](https://cloud.githubusercontent.com/assets/6170607/18030191/100cbfee-6cae-11e6-9de7-da527c7b9693.png)?

**Comment by sindresorhus** [comment] 2016-08-27 21:51
Tried your linter config. Same result. I'll try to think of a reason you get this, but it's pretty weird that I can't reproduce.

**Comment by jfmengels** [comment] 2016-08-28 20:25
Can't reproduce it either :confused:.
Does it happen only in the editor, or also when you run `xo` with the CLI? (Can't reproduce with either, but still)

**Comment by nesukun** [comment] 2016-10-16 17:51
Just saw this happening to me too, config is as follows:

```
  "xo": {
    "envs": [
      "browser",
      "node"
    ],
    "esnext": true,
    "ignores": [
      "static/**"
    ],
    "parser": "babel-eslint",
    "plugins": [
        "babel"
    ],
    "space": 2,
    "rules": {
      "babel/new-cap": [
        2
      ],
      "import/no-unassigned-import": [
        0
      ],
      "import/prefer-default-export": [
        0
      ],
      "new-cap": [
        0
      ],
      "padded-blocks": [
        2,
        "always"
      ],
      "no-implicit-coercion": [
        2,
        {
          "boolean": false
        }
      ],
      "no-negated-condition": [
        0
      ],
      "no-unused-expressions": [
        2,
        {
          "allowShortCircuit": true
        }
      ],
      "no-unused-vars": [
        2,
        {
          "vars": "all",
          "args": "none"
        }
      ],
      "object-curly-spacing": [
        2,
        "always"
      ]
    }
  }
```

Getting:
```
  test\server\core\auth.js:1:1
  ×    1:1   Test file is ignored because it is not in test/*/.                                                       ava/no-ignored-test-files
```

running just `xo` on the console. lastest node, xo, and other packages (I'm on Windows 10 tho)

**Comment by marionebl** [comment] 2016-11-25 15:56
@leo Is this still an issue with the latest version of `linter-xo`?

**Comment by marionebl** [comment] 2016-12-13 02:11
Tried to reproduce without success:

```sh
git clone https://github.com/leo/args.git
cd args
npm install
vim package.json # remove line 53
atom . # open test/index.js
```

```
❯ atom -v
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

❯ apm ls | grep linter-xo
└── linter-xo@0.21.1
```

Closing this for now. Reopen if this persists - please provide `atom` and `linter-xo` package versions then.

**Closed by marionebl** 2016-12-13 02:11 UTC
