### ISSUE TITLE
unicorn rules not found in atom-beta

### ISSUE THREAD

**Issue by tony-kerz** [sindresorhus/atom-linter-xo#74] opened 2017-04-28 02:53 UTC
just an fyi, in case you haven't come across it yet, what i'm seeing in atom-beta:

<img width="712" alt="screen shot 2017-04-27 at 10 50 13 pm" src="https://cloud.githubusercontent.com/assets/1223231/25512484/1a5c1e2e-2b9c-11e7-8812-40313982bd08.png">

**Comment by ApricumMedia** [comment] 2017-04-29 08:22
Going to reference this here, posted the _same issue_ on the XO repository a few days back: https://github.com/sindresorhus/xo/issues/214

I though it was my mistake using `nvm` which may messed up various "node_modules" directories but **if you're not using `nvm`**, we can exclude that.

**Comment by ApricumMedia** [comment] 2017-04-30 14:40
After some testing yesterday, I can confirm that the issue only surfaces in the Atom Beta, not the regular version.

**Comment by rockymadden** [comment] 2017-05-16 16:57
Atom `1.17.0` was just published, observing this issue in non-beta.

**Comment by forivall** [comment] 2017-05-16 21:36
After some time in the debugger, this looks like an issue with https://github.com/atom/atom/pull/13916 . When xo requires `eslint-plugin-unicorn`, somehow, `eslint-plugin-ava` is returned.

**Comment by tony-kerz** [comment] 2017-05-19 18:41
as a stop gap, i've placed this in `package.json`:
```
  "xo": {
...
    "rules": {
...
      "unicorn/no-new-buffer": "off",
      "unicorn/filename-case": "off",
      "unicorn/custom-error-definition": "off",
      "unicorn/no-array-instanceof": "off",
      "unicorn/catch-error-name": "off",
      "unicorn/no-process-exit": "off",
      "unicorn/throw-new-error": "off",
      "unicorn/number-literal-case": "off",
      "unicorn/prefer-starts-ends-with": "off",
      "unicorn/prefer-type-error": "off",
      "unicorn/explicit-length-check": "off",
      "unicorn/no-abusive-eslint-disable": "off"
    }
  }
```
annoying to type, so in case anyone else wants to clip as a temp workaround...

**Comment by Rowno** [comment] 2017-06-17 05:31
I found the source of the bug, it's actually in the `req-all` (now called `import-modules`) module. When it's first required it initialises a [fixed parentDir variable](https://github.com/sindresorhus/import-modules/blob/v1.0.0/index.js#L8). Since both [`eslint-plugin-ava`](https://github.com/avajs/eslint-plugin-ava/blob/v4.2.0/index.js#L5) and [`eslint-plugin-unicorn`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v2.1.1/index.js#L5) use it the module the `parentDir` gets set to `[project path]/node_modules/eslint-plugin-ava` (since it loads first) and then when it's called in `eslint-plugin-unicorn` it ends up resolving the rules from `eslint-plugin-ava`.

**Comment by Rowno** [comment] 2017-06-17 05:43
These two pull requests should fix the bug:
https://github.com/avajs/eslint-plugin-ava/pull/175
https://github.com/sindresorhus/eslint-plugin-unicorn/pull/95

**Comment by ApricumMedia** [comment] 2017-06-17 07:14
Thank you so much for your detective work, Rowno! I hope the plugin maintainers take a peek into it this weekend.

**Comment by sindresorhus** [comment] 2017-06-17 09:16
Thanks for looking into and fixing this @Rowno. I really appreciate it. 🙌

**Closed** 2017-06-17 09:15 UTC

**Comment by tony-kerz** [comment] 2017-06-17 15:53
echo thanks @Rowno !

any guidance around options for picking up this change via atom-linter-xo (i.e. do i need to wait for one or more new package releases, or is there a pragmatic way for me to reference pre-release commits of one or more packages)?

**Comment by sindresorhus** [comment] 2017-06-17 16:04
@tony-kerz Reinstall `atom-linter-xo`.

**Comment by Rowno** [comment] 2017-06-17 19:39
Also if you're using Yarn, you'll need remove and re-add `xo` so that all of it's sub-dependencies get updated.

**Comment by zenopopovici** [comment] 2017-06-19 14:50
Still doesn't work for me. I reinstalled everything, I still get the errors.

**Comment by forivall** [comment] 2017-06-19 16:20
@zenopopovici what's the output of `npm ls eslint-plugin-ava eslint-plugin-unicorn` ?

**Comment by Rowno** [comment] 2017-06-19 18:11
@zenopopovici FYI, you'll also need to restart Atom after upgrading `eslint-plugin-ava` and `eslint-plugin-unicorn`.

**Comment by zenopopovici** [comment] 2017-06-19 18:26
@Rowno, @forivall 
  ├── eslint-plugin-ava@4.2.0 
  └── eslint-plugin-unicorn@2.1.1

**Comment by Rowno** [comment] 2017-06-19 18:42
You need `eslint-plugin-ava@4.2.1` and `eslint-plugin-unicorn@2.1.2` in your project to fix the errors.

**Comment by zenopopovici** [comment] 2017-06-19 20:35
@Rowno Thanks. I can confirm that I'm stupid :)

**Comment by OmgImAlexis** [comment] 2017-07-25 06:07
I've got the required versions and yet I still have the issue.
```
➜  shelf git:(master) ✗ npm ls eslint-plugin-ava eslint-plugin-unicorn
shelf@0.0.0 /Users/xo/code/shelf
└─┬ xo@0.18.2
  ├── eslint-plugin-ava@4.2.1 
  └── eslint-plugin-unicorn@2.1.2 
```

**Comment by OmgImAlexis** [comment] 2017-07-25 06:15
Found my issue, you also need to update your global version of it as it seems that's what atom uses.
